train:
  _target_: src.datasets.NVDataset
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.NVDataset
  part: "val"
  instance_transforms: ${transforms.instance_transforms.val}
  is_val: True
