defaults:
  - generator: generator
  - mpd: mpd
  - msd: msd
  - metrics: example
  - datasets: custom_dir # we do not want to run inference on training data
  - dataloader: inference
  - transforms: nv
  - _self_
inferencer:
  device_tensors: ["spectrogram"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "vocoder_generated" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "models/vocoder_V1/checkpoint.pth" # path to the pretrained model
