_target_: src.logger.CometMLWriter
project_name: "HiFiGAN"
workspace: null
run_name: "test"
mode: "online"
loss_names: ["loss", "mpd_feature_loss", "msd_feature_loss", "mpd_gan_loss", "msd_gan_loss", "mel_loss", "msd_loss", "mpd_loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
